[package]
name = "para_test"
version = "0.1.0"
authors = ["sriram1999s <sriramsub7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
rayon = "1.5.1"
termion = "1.0.0"
