[package]
name = "para_test"
version = "0.1.0"
authors = ["sriram1999s <sriramsub7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
